'use server';
/**
 * @fileOverview A Genkit flow for verifying the halal compliance of a product.
 *
 * - verifyHalalProduct - A function that handles the halal product verification process.
 * - VerifyHalalProductInput - The input type for the verifyHalalProduct function.
 * - VerifyHalalProductOutput - The return type for the verifyHalalProduct function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const VerifyHalalProductInputSchema = z.object({
  ingredients: z.string().describe('The full ingredient list of the product.'),
  certifications: z
    .string()
    .optional()
    .describe('Any known halal certifications for the product, if available.'),
  productPhotoDataUri: z
    .string()
    .optional()
    .describe(
      "An optional photo of the product, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type VerifyHalalProductInput = z.infer<typeof VerifyHalalProductInputSchema>;

const VerifyHalalProductOutputSchema = z.object({
  halalStatus: z
    .enum(['HALAL', 'HARAM', 'MASHBOOH', 'UNKNOWN'])
    .describe(
      'The overall halal compliance status of the product. HALAL means permissible, HARAM means forbidden, MASHBOOH means questionable/doubtful, UNKNOWN means not enough information to determine.'
    ),
  confidenceScore: z
    .number()
    .min(0)
    .max(100)
    .describe(
      'A confidence score (0-100) indicating the AI\'s certainty in its assessment. Lower scores indicate more uncertainty.'
    ),
  explanation: z
    .string()
    .describe(
      'A detailed explanation of the assessment, including specific ingredients or factors that raised concerns or confirmed compliance.'
    ),
  unvalidatedWarning: z
    .string()
    .describe(
      'A static warning stating that the information is unvalidated and risks are associated with it.'
    ),
});
export type VerifyHalalProductOutput = z.infer<typeof VerifyHalalProductOutputSchema>;

export async function verifyHalalProduct(
  input: VerifyHalalProductInput
): Promise<VerifyHalalProductOutput> {
  return productHalalVerifierFlow(input);
}

const prompt = ai.definePrompt({
  name: 'productHalalVerifierPrompt',
  input: {schema: VerifyHalalProductInputSchema},
  output: {schema: VerifyHalalProductOutputSchema},
  prompt: `You are an expert in halal dietary laws and food science. Your task is to analyze product information to determine its halal compliance. Based on the provided ingredients and certifications, assess the product's halal status, provide a confidence score, and explain your reasoning.

Critically examine the ingredients for any haram (forbidden) or mashbooh (questionable) substances. Consider the source and processing of ingredients such as gelatin, enzymes, emulsifiers, alcohols, and any animal-derived products.

If certifications are provided, analyze their credibility and how they contribute to the overall halal status. If no certifications are present, or if they are unclear, factor that into your assessment.

Your output MUST include:
1. A 'halalStatus' (HALAL, HARAM, MASHBOOH, or UNKNOWN).
2. A 'confidenceScore' (0-100) reflecting your certainty. A lower score means more uncertainty, especially if key information is missing or ambiguous.
3. A detailed 'explanation' justifying your assessment, highlighting specific concerns or confirmations.
4. A 'unvalidatedWarning' which is always the following exact phrase: "This information is generated by AI and has not been validated by human experts. It is for informational purposes only, and users should exercise their own judgment and consult with religious scholars or certified authorities for definitive guidance. The app makes no guarantees regarding halal compliance based on this AI analysis."

--- Product Details ---
Ingredients: {{{ingredients}}}

{{#if certifications}}
Certifications: {{{certifications}}}
{{else}}
Certifications: None provided.
{{/if}}

{{#if productPhotoDataUri}}
Product Photo: {{media url=productPhotoDataUri}}
{{else}}
Product Photo: No photo provided.
{{/if}}

`,
});

const productHalalVerifierFlow = ai.defineFlow(
  {
    name: 'productHalalVerifierFlow',
    inputSchema: VerifyHalalProductInputSchema,
    outputSchema: VerifyHalalProductOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
