-- ============================================================
-- Halal Hub — Sample Businesses Seed
-- Run in Supabase SQL editor to populate all category listings
-- All records are status='active' and safe to delete/re-run
-- ============================================================

-- Clear existing seed data (identified by source comment in description)
DELETE FROM public.businesses WHERE description LIKE '%[seed]%';

-- ── Meat & Butchers ─────────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open) VALUES
('Al-Barakah Premium Meats',   'Meat & Butchers', 'Wholesale & Retail',       'Andheri West', 'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Wagyu Beef','Dry-aged Lamb','Custom Cuts'],        'HMC Certified premium meat supplier with full traceability. [seed]', 'active', true),
('Tayyib Butchers',            'Meat & Butchers', 'Family Butcher',            'Kurla',         'Mumbai', 4.7, true,  'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Free-range Chicken','Custom Orders','Weekly Boxes'], 'HFA Approved family-run butcher with ethically sourced meat. [seed]', 'active', true),
('Organic Halal Farm',         'Meat & Butchers', 'Farm-to-Door',              'Pune',          'Maharashtra', 4.8, true,  'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['100% Grass-fed','Traceability Logs','Subscription Box'], 'Organic certified farm delivering directly to your door. [seed]', 'active', true),
('Quick Halal Cuts',           'Meat & Butchers', 'Quick Service Butcher',     'Dharavi',       'Mumbai', 4.4, false, 'https://images.unsplash.com/photo-1529543544282-ea669407fca3?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Walk-in','Affordable Bulk','Same-day Ready'],          'Convenient walk-in butcher for everyday halal needs. [seed]', 'active', true),
('Crown Halal Meats',          'Meat & Butchers', 'Premium Butcher',           'Bandra',        'Mumbai', 4.6, true,  'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['HMC Certified','Home Delivery','Special Cuts'],        'Trusted premium butcher serving Mumbai for 20+ years. [seed]', 'active', false),
('Bismillah Fresh Cuts',       'Meat & Butchers', 'Neighbourhood Butcher',     'Thane',         'Mumbai', 4.5, true,  'https://images.unsplash.com/photo-1603048588665-791ca8aea617?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Daily Fresh Stock','Marinating Service','Budget-friendly'], 'Fresh halal cuts daily with optional marinating service. [seed]', 'active', true);

-- ── Hotels & Accommodation ───────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open, price_range) VALUES
('Royal Halal Suites',         'Hotels & Accommodation', 'Boutique Hotel',          'Bandra',       'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Prayer Hall','Gourmet Halal Breakfast','Strictly Alcohol-Free'], 'Luxury suites with full halal hospitality standards. [seed]', 'active', true, '₹350/night'),
('Zaytoun Boutique Hotel',     'Hotels & Accommodation', 'Boutique Hotel',          'Colaba',       'Mumbai', 4.7, true,  'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Qibla Compasses','No Mixed Pool','Halal Restaurant On-site'], 'Heritage boutique with thoughtful halal amenities. [seed]', 'active', true, '₹220/night'),
('Al-Ansar Budget Stays',      'Hotels & Accommodation', 'Budget Guesthouse',       'Kurla',        'Mumbai', 4.3, false, 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['24hr Reception','Free Breakfast','Near Mosque'],           'Affordable clean accommodation for Muslim travellers. [seed]', 'active', true, '₹80/night'),
('Makkah Grand Hotel',         'Hotels & Accommodation', '5-Star Hotel',            'Andheri West', 'Mumbai', 4.8, true,  'https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Rooftop Prayer Space','Separate Gym Timings','Halal Fine Dining'], 'Five-star experience built on Islamic values. [seed]', 'active', true, '₹600/night'),
('Modest Inn Collection',      'Hotels & Accommodation', 'Serviced Apartments',     'Powai',        'Mumbai', 4.5, true,  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Self-catering Kitchen','Long Stay Discounts','Family Suites'], 'Fully equipped serviced apartments for extended stays. [seed]', 'active', true, '₹180/night'),
('Baraka Heritage Lodge',      'Hotels & Accommodation', 'Heritage Property',       'Bhopal',       'Madhya Pradesh', 4.6, true,  'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Mughal Architecture','Halal Chef','Cultural Tours'], 'Restored heritage property with authentic Islamic architecture. [seed]', 'active', true, '₹250/night');

-- ── Beauty & Cosmetics ───────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open, price_range) VALUES
('Pure Glow Cosmetics',        'Beauty & Cosmetics', 'Premium Skincare',      'Dubai',  'UAE',    4.9, true,  'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Lab Verified','Vegan Formula','Alcohol Free'],           'Award-winning halal skincare certified by IFANCA. [seed]', 'active', true, '₹45'),
('Noor Beauty Labs',           'Beauty & Cosmetics', 'Makeup & Color',        'London', 'UK',     4.8, true,  'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Pork-free','Cruelty-Free','Wudhu-Friendly'],            'High-pigment halal makeup for the modern Muslimah. [seed]', 'active', true, '£18'),
('Zahra Natural Skincare',     'Beauty & Cosmetics', 'Natural & Organic',     'Karachi','Pakistan',4.7, true,  'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Botanical Ingredients','Fragrance Free','Sensitive Skin'],'100% natural ingredients sourced from Islamic tradition. [seed]', 'active', true, '₹38'),
('Halal Glow Studio',          'Beauty & Cosmetics', 'Beauty Salon',          'Mumbai', 'India',  4.6, true,  'https://images.unsplash.com/photo-1560066984-138dadb4c035?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Female-Only','Hijab-Friendly','Organic Products'],       'Muslim women-only salon with 100% halal beauty services. [seed]', 'active', true, '₹800'),
('Modest Scents Arabia',       'Beauty & Cosmetics', 'Perfumery & Oud',       'Jeddah', 'Saudi Arabia', 4.9, true, 'https://images.unsplash.com/photo-1547887537-6158d64c35b3?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Alcohol-Free Perfume','Oud Collections','Custom Blending'], 'Authentic Arabian oud and attar without alcohol. [seed]', 'active', true, '₹120'),
('Sunnah Skincare',            'Beauty & Cosmetics', 'Prophetic Remedies',    'Istanbul','Turkey', 4.5, true,  'https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Black Seed Oil','Sidr Honey','Miswak Products'],         'Skincare rooted in Prophetic medicine and natural healing. [seed]', 'active', true, '₹55');

-- ── Catering Services ────────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open) VALUES
('Elite Halal Catering',       'Catering Services', 'Full-Service Events',    'Bandra',       'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1555244162-803834f70033?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Live Stations','Uniformed Staff','Cutlery Rental'],      'Full-service event catering for 50–1000 guests. [seed]', 'active', true),
('Sunnah Saffron Catering',    'Catering Services', 'Boutique & Private',     'Andheri West', 'Mumbai', 4.8, true,  'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Organic Ingredients','Custom Menus','Small Gatherings'], 'Boutique caterer specialising in intimate gatherings. [seed]', 'active', true),
('Baraka Home Kitchens',       'Catering Services', 'Home-style Catering',    'Kurla',        'Mumbai', 4.6, true,  'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Home Recipes','Affordable','Tasting Sessions'],          'Authentic home-style halal cooking for all occasions. [seed]', 'active', true),
('Al-Noor Wedding Catering',   'Catering Services', 'Wedding Specialist',     'Thane',        'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1555244162-803834f70033?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['5-Course Menus','Floral Arrangements','Separate Seating'], 'Premier wedding catering with full Islamic ceremony support. [seed]', 'active', true),
('Halal Express Catering',     'Catering Services', 'Corporate & Office',     'Worli',        'Mumbai', 4.5, false, 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Same-day Orders','Box Meals','Office Delivery'],          'Fast corporate catering with daily halal menus. [seed]', 'active', true),
('Ummah Feast Catering',       'Catering Services', 'Community Events',       'Dharavi',      'Mumbai', 4.4, true,  'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Masjid Events','Community Iftars','Budget Packages'],    'Community-focused catering for mosques and Islamic events. [seed]', 'active', false);

-- ── Media & Publishing ───────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open, price_range) VALUES
('Noor Islamic Media',         'Media & Publishing', 'Publisher & Bookstore',  'London',   'UK',      4.9, true,  'https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Classic Editions','Author Signings','Digital App'],       'Leading Islamic publisher with 2000+ titles. [seed]', 'active', true, '£12.00'),
('Muslim Voices Podcast',      'Media & Publishing', 'Podcast Network',        'New York',  'USA',     4.7, true,  'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['200+ Episodes','Scholar Interviews','Free Library'],      'Top-ranked Muslim podcast network reaching 1M+ listeners. [seed]', 'active', true, 'Free'),
('Quran House Publications',   'Media & Publishing', 'Quran & Islamic Books',  'Cairo',     'Egypt',   4.8, true,  'https://images.unsplash.com/photo-1553531384-cc64ac80f931?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Certified Prints','Multilingual','Braille Available'],    'High-quality Quran printing with ijazah-certified editions. [seed]', 'active', true, '₹25'),
('Crescent Digital Magazine',  'Media & Publishing', 'Digital Magazine',       'Dubai',     'UAE',     4.6, true,  'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Weekly Issues','Muslim Lifestyle','Global Stories'],      'Premier Muslim lifestyle magazine covering faith and culture. [seed]', 'active', true, '₹8/mo'),
('Islamic Arts Collective',    'Media & Publishing', 'Art & Creative Media',   'Istanbul',  'Turkey',  4.9, true,  'https://images.unsplash.com/photo-1547981609-4b6bfe67ca0b?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Calligraphy','Geometric Art','Exhibition Prints'],        'Islamic geometric art and calligraphy for homes and gifting. [seed]', 'active', true, '₹35'),
('Ummah Radio Network',        'Media & Publishing', 'Radio & Audio',          'Manchester','UK',      4.5, true,  'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Live Broadcasts','Nasheed Playlists','Community Show'],  '24/7 Muslim community radio featuring news, nasheeds, and talks. [seed]', 'active', true, 'Free');

-- ── Grocery & Supermarkets ───────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open) VALUES
('Amanah Hypermarket',         'Grocery & Supermarkets', 'Full Service Hypermarket', 'Kurla',       'Mumbai', 4.8, true,  'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Meat Counter','Fresh Bakery','Organic Section'],           'Mumbai''s largest halal-only supermarket. [seed]', 'active', true),
('Al-Falah Fresh Market',      'Grocery & Supermarkets', 'Fresh Produce Market',     'Andheri West','Mumbai', 4.7, true,  'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Daily Fresh Produce','Local Farms','No Additives'],       'Farm-fresh produce delivered daily to our halal market. [seed]', 'active', true),
('Baraka Online Grocers',      'Grocery & Supermarkets', 'Online Delivery',           'Bandra',      'Mumbai', 4.6, true,  'https://images.unsplash.com/photo-1601598851547-4302969d0614?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['2-Hour Delivery','Subscription Boxes','Import Goods'],    'Online halal grocery delivery across Mumbai in 2 hours. [seed]', 'active', true),
('Madinah Organic Store',      'Grocery & Supermarkets', 'Organic & Health Foods',   'Colaba',      'Mumbai', 4.8, false, 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['USDA Organic','No Pork Derivatives','Supplement Range'], 'Organic halal-friendly health food store. [seed]', 'active', false),
('Muslim Pantry',              'Grocery & Supermarkets', 'Specialty Imports',         'Thane',       'Mumbai', 4.5, true,  'https://images.unsplash.com/photo-1488459716781-31db52582fe9?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Middle Eastern Imports','Ethnic Spices','Prayer Items'],  'Specialty importer of Middle Eastern and South Asian halal goods. [seed]', 'active', true),
('Halal Corner Store',         'Grocery & Supermarkets', 'Neighbourhood Grocery',    'Dharavi',     'Mumbai', 4.3, true,  'https://images.unsplash.com/photo-1601598851547-4302969d0614?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Walk-in','Open Late','Affordable Basics'],                'Your local halal corner shop — open every day. [seed]', 'active', true);

-- ── Events & Venues ─────────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open, price_range) VALUES
('The Grand Halal Ballroom',   'Events & Venues', 'Premium Venue',         'Bandra',       'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Prayer Room','Female-Only Staff Option','Halal Catering'],  'Grand ballroom for weddings, walimas, and corporate events. [seed]', 'active', true, 'From ₹2,500'),
('Modest Moments Photography', 'Events & Venues', 'Photography & Cinema',  'Andheri West', 'Mumbai', 4.8, true,  'https://images.unsplash.com/photo-1554080353-a576cf803bda?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Female Photographer','Privacy Guaranteed','Same-day Previews'], 'Muslim wedding photography with full privacy options. [seed]', 'active', true, 'From ₹1,200'),
('Al-Kawthar Gardens',         'Events & Venues', 'Garden & Outdoor Venue','Powai',        'Mumbai', 4.7, true,  'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Garden Setting','Wudhu Facilities','Alcohol-Free Policy'],  'Beautiful outdoor venue for nikkahs and family celebrations. [seed]', 'active', true, 'From ₹1,800'),
('Nikkah Planning Co.',        'Events & Venues', 'Wedding Planner',       'Thane',        'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1519167758481-83f550bb49b3?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['End-to-End Planning','Scholar Coordination','Floral Decor'], 'Full-service Islamic wedding planning from nikah to walima. [seed]', 'active', true, 'From ₹5,000'),
('Islamic Events Tent',        'Events & Venues', 'Community Events',      'Kurla',        'Mumbai', 4.4, false, 'https://images.unsplash.com/photo-1505236858219-8359eb29e329?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Ramadan Events','Eid Melas','Community Iftars'],           'Large tent hire for community Islamic events and iftars. [seed]', 'active', true, 'From ₹800');

-- ── Fashion & Modest Wear ────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open, price_range) VALUES
('Modest Attire Co.',          'Fashion & Modest Wear', 'Premium Designer',       'London',   'UK',      4.9, true,  'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Global Shipping','Sizing Guide','Silk Fabrics'],          'Award-winning modest fashion for the modern Muslimah. [seed]', 'active', true, '£120'),
('Sunnah Threads',             'Fashion & Modest Wear', 'Everyday Modest Wear',  'Manchester','UK',      4.7, true,  'https://images.unsplash.com/photo-1612307057748-b44842539a29?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Affordable Range','Size-Inclusive','Ethical Supply'],     'Everyday modest clothing for the whole family. [seed]', 'active', true, '£35'),
('Abaya Palace',               'Fashion & Modest Wear', 'Abayas & Outer Wear',   'Dubai',    'UAE',     4.8, true,  'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['1000+ Styles','Custom Embroidery','Same-day Dispatch'],   'The world''s largest online abaya collection. [seed]', 'active', true, '₹65'),
('Hijab Couture Dubai',        'Fashion & Modest Wear', 'Hijab & Headwear',      'Dubai',    'UAE',     4.9, true,  'https://images.unsplash.com/photo-1612307057748-b44842539a29?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Premium Chiffon','Colour Matching','Wedding Sets'],       'Luxury hijab and headscarf collections for every occasion. [seed]', 'active', true, '₹45'),
('Modest Kids Fashion',        'Fashion & Modest Wear', 'Children''s Wear',       'Istanbul', 'Turkey',  4.6, true,  'https://images.unsplash.com/photo-1445205170230-053b83016050?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Soft Fabrics','Playful Designs','Islamic Prints'],        'Islamic-inspired modest clothing for children aged 0–14. [seed]', 'active', true, '₹28'),
('Thobe & Kurta House',        'Fashion & Modest Wear', 'Menswear',              'Mumbai',   'India',   4.5, true,  'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Custom Stitching','Eid Collections','Saudi Style'],       'Premium thobes, kurtis and sherwanis for Muslim men. [seed]', 'active', true, '₹40');

-- ── Healthcare & Wellness ────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open) VALUES
('Safe Care Medical Hub',      'Healthcare & Wellness', 'Multi-Specialty Clinic', 'Andheri West','Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Female Doctors','Gender Segregated','Prayer Room'],      'Muslim-sensitive multi-specialty clinic with gender segregation. [seed]', 'active', true),
('Al-Shifa Family Clinic',     'Healthcare & Wellness', 'Family Medicine',        'Bandra',      'Mumbai', 4.7, true,  'https://images.unsplash.com/photo-1559757175-0eb30cd8c063?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Home Visits','Halal Medicines','Multilingual Staff'],     'Caring family clinic sensitive to Islamic medical ethics. [seed]', 'active', true),
('Healing Hands Physio',       'Healthcare & Wellness', 'Physiotherapy',          'Kurla',       'Mumbai', 4.6, false, 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Same-Gender Therapists','Sports Rehab','Post-natal Care'], 'Specialist physiotherapy with gender-aware treatment options. [seed]', 'active', true),
('Islamic Counseling Centre',  'Healthcare & Wellness', 'Mental Health',          'Colaba',      'Mumbai', 4.8, true,  'https://images.unsplash.com/photo-1527689368864-3a821dbccc34?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Islamic Perspective','Ruqyah Sessions','Online Therapy'],  'Faith-integrated counselling rooted in Islamic values. [seed]', 'active', true),
('Noor Dental Care',           'Healthcare & Wellness', 'Dentistry',              'Thane',       'Mumbai', 4.5, true,  'https://images.unsplash.com/photo-1588776814546-1ffedbe47425?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Halal Anaesthetics','Female Dentists','Child-friendly'],  'Family dental practice using only halal-certified materials. [seed]', 'active', false),
('Sunnah Wellness Centre',     'Healthcare & Wellness', 'Holistic & Prophetic',   'Powai',       'Mumbai', 4.7, true,  'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Hijama Therapy','Black Seed Treatments','Ruqyah'],        'Prophetic medicine and holistic healing for mind, body, and soul. [seed]', 'active', true);

-- ── Islamic Finance ─────────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open) VALUES
('Amanah Islamic Bank',        'Islamic Finance', 'Retail Banking',           'Mumbai',      'India', 4.9, true,  'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Shariah Audited','Mudarabah Funds','Zakat Tools'],         'Full-service Islamic retail bank with Shariah supervisory board. [seed]', 'active', true),
('Halal Mortgage Advisors',    'Islamic Finance', 'Home Finance',             'London',      'UK',    4.8, true,  'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Murabaha','Ijara','Diminishing Musharakah'],               'Independent advisors for Shariah-compliant home financing. [seed]', 'active', true),
('Zakat Fintech Solutions',    'Islamic Finance', 'Zakat & Charity Tech',     'Karachi',     'Pakistan',4.7, true,  'https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Auto Zakat Calculator','AAOIFI Compliant','Annual Report'], 'Technology platform for automated zakat calculation and distribution. [seed]', 'active', true),
('Takaful Insurance Group',    'Islamic Finance', 'Takaful Insurance',        'Kuala Lumpur','Malaysia',4.6, true,  'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Life Takaful','Family Cover','Transparent Surplus'],       'Islamic cooperative insurance with full surplus distribution. [seed]', 'active', true),
('Shariah Invest',             'Islamic Finance', 'Investment Platform',      'Dubai',       'UAE',   4.7, true,  'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Screened Equities','Sukuk Bonds','Purification Engine'],   'Shariah-screened investment portfolio with automatic purification. [seed]', 'active', true),
('Waqf Land Trust',            'Islamic Finance', 'Waqf & Endowments',        'Mumbai',      'India', 4.5, true,  'https://images.unsplash.com/photo-1554224155-6726b3ff858f?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Property Waqf','Education Endowments','Annual Returns'],    'Managing waqf properties and Islamic endowments since 1998. [seed]', 'active', false);

-- ── Travel & Tourism ────────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open) VALUES
('Saffron Travels',            'Travel & Tourism', 'Premium Agency',          'Bandra',       'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Certified Guides','Halal Board Included','Visa Support'],  'Premium halal travel packages to Turkey, UAE & Jordan. [seed]', 'active', true),
('Al-Huda Pilgrimages',        'Travel & Tourism', 'Hajj & Umrah Specialist', 'Andheri West', 'Mumbai', 4.8, true,  'https://images.unsplash.com/photo-1580418827493-f2b22c0a76cb?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['5-Star Hotels','Religious Scholars','Medical Support'],     'Trusted Hajj and Umrah operator with 25 years of experience. [seed]', 'active', true),
('Ummah Travel Network',       'Travel & Tourism', 'Muslim-Friendly Holidays','Kurla',        'Mumbai', 4.6, true,  'https://images.unsplash.com/photo-1488085061387-422e29b40080?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Prayer-Friendly Hotels','Halal Restaurants Guide','Family Tours'], 'Curated Muslim-friendly holidays worldwide. [seed]', 'active', true),
('Halal Holiday Planner',      'Travel & Tourism', 'Online Travel Portal',    'Thane',        'Mumbai', 4.5, false, 'https://images.unsplash.com/photo-1530789253388-582c481c54b0?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Compare Packages','Instant Booking','Refund Guarantee'],  'Compare and book halal travel packages online. [seed]', 'active', true),
('Crescent Adventures',        'Travel & Tourism', 'Adventure & Eco Tours',   'Powai',        'Mumbai', 4.7, true,  'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Halal Camping','Nature Hikes','Eco-Certified'],           'Halal adventure tourism in India''s most stunning landscapes. [seed]', 'active', true),
('Ziyarat Travel Experts',     'Travel & Tourism', 'Religious & Heritage',    'Colaba',       'Mumbai', 4.8, true,  'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Scholar-Led Tours','Historical Sites','Dawah Travel'],   'Expert-guided ziyarat tours to Islamic heritage sites worldwide. [seed]', 'active', false);

-- ── Education & Learning ─────────────────────────────────────────────────────
INSERT INTO public.businesses (name, category, subcategory, city, country, rating, halal_verified, image_url, selected_highlights, description, status, is_open) VALUES
('Iman Knowledge Academy',     'Education & Learning', 'Academic & Islamic School',  'Bandra',       'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Hifz Program','STEM Curriculum','Sports Facilities'],    'K-12 school integrating Islamic values with academic excellence. [seed]', 'active', true),
('Al-Azhar Online Institute',  'Education & Learning', 'Online Islamic Studies',    'Cairo',        'Egypt',  4.8, true,  'https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Accredited Degrees','Live Classes','Arabic & English'],  'Online Islamic university affiliated with Al-Azhar scholars. [seed]', 'active', true),
('Quran Memorization Academy', 'Education & Learning', 'Hifz & Tajweed',            'Andheri West', 'Mumbai', 4.9, true,  'https://images.unsplash.com/photo-1609234656432-603ebd98fb83?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Expert Huffadh','Ijazah Certification','Online & In-person'], 'World-class Quran memorisation with ijazah certification. [seed]', 'active', true),
('Muslim Homeschool Network',  'Education & Learning', 'Homeschooling Support',     'Thane',        'Mumbai', 4.6, true,  'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Curriculum Packages','Parent Community','Halal Assessment'], 'Full support network for Muslim families choosing homeschooling. [seed]', 'active', true),
('Islamic Business School',    'Education & Learning', 'Higher Education & MBA',    'Kuala Lumpur', 'Malaysia',4.7, true,  'https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Islamic Finance MBA','Ethical Leadership','Industry Links'], 'Postgraduate business education rooted in Islamic ethics. [seed]', 'active', true),
('Little Scholars Preschool',  'Education & Learning', 'Early Childhood',           'Kurla',        'Mumbai', 4.5, true,  'https://images.unsplash.com/photo-1526662092594-e98c1e356d6a?w=800&h=600&fit=crop&auto=format&q=80', ARRAY['Islamic Nursery Rhymes','Quran Basics','Play-based Learning'], 'Nurturing Islamic preschool environment for children aged 2–5. [seed]', 'active', false);
